VisionPlayer/app.py
from flask import *
from flask_socketio import SocketIO
from blueprints import play
from sockets import comment

app = Flask(__name__)
app.config['SECRET_KEY'] = '123456'
socketio = SocketIO(app)
@app.route('/')
def index():
    return redirect(url_for("play.index"))

app.register_blueprint(play.bp)


comment.register_comment(socketio)

if __name__ == '__main__':
    # app.run(host='0.0.0.0', port=80, debug=True, threaded='True')
    socketio.run(app, host='0.0.0.0', port=888, debug=True)

VisionPlayer/blueprints/play.py
from flask import *
from utils.func import random_name, file_extension, now
from utils.video_frame import capture
from utils.music_list import getMusic

bp = Blueprint('play',__name__,url_prefix="/play")

@bp.route('/upload', methods=['GET'])
def upload():
    return render_template('play/upload.html')

@bp.route('/music/upload', methods=['POST'])
def doupload():
    id = random_name()

    video = request.files['video']
    video.save('static/video/' + id  + file_extension(video.filename))

    # image = request.files['image']
    # image.save('static/image/' + id + file_extension(image.filename))

    image = 'static/image/' + id + '.jpg'
    capture('static/video/' + id  + file_extension(video.filename), image)

    data = {
        "author": request.form["author"],
        "date": now(),
        "image": "/" + image,
        "video": "/static/video/" + id  + file_extension(video.filename),
        "title": request.form["title"]
        # "description": request.form["description"]
    }
    with open("static/upload/" + id + ".json", "w") as f:
        json.dump(data, f)

    return redirect(url_for('play.index'))


@bp.route('/')
def index():
    music_list = getMusic('static/upload')
    return render_template('play/player.html', musicList=music_list)

VisionPlayer/templates/play/player.html
<!doctype html>
<html>

	<head>
		<meta charset="utf-8">
		<title>Station de partage vidéo</title>
		<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
		<link rel="stylesheet" type="text/css" href="/static/css/common.css">
		<script src="/static/js/jquery-1.12.1.min.js"></script>
	</head>

	<body>

		<div class="videos">
			<div class="video_b" style="margin-top:0">
				<div class="video_b_in">

					{% include 'video.html' %}

					<div class="video_rs">

						<div class="video_rs_t">
							<span>Liste des vidéos</span>
							<b style="color:red;font-size: 16px">Je veux partager la vidéo→</b>
							<a href="{{ url_for('play.upload') }}">
								<div class="btnadd">upload</div>
							</a>
						</div>

						<div class="video_rs_b">

							{% for item in musicList %}
							<div class="one_tb" vid_src="{{ item.video }}">
								<span class="one_tb_l">{{loop.index}}</span>
								<div class="one_tb_c">
									<img src="{{ item.image }}">
									<b></b>
								</div>
								<div class="one_tb_r">
									<h3 title="{{ item.title }}">{{ item.title }}</h3>
									<!--<p title="{{ item.description }}">{{ item.description }}</p>-->
									<p>{{ item.date }} &nbsp;&nbsp;{{ item.author }} </p>
								</div>
							</div>
							{% endfor %}

						</div>
					</div>
				</div>
			</div>
		</div>

		<script>
			$(document).ready(function() {
				$('.one_tb').eq(0).click();
			});

			$(".one_tb").click(function() {
				$(this).addClass("on").siblings(".one_tb").removeClass("on");
				var hName = $(this).find("h3").html();
				var vid_src = $(this).attr("vid_src");
				$(".title_top").html(hName);
				vids.src = vid_src;
				vids.play();
			});
		</script>
	</body>

</html>

VisionPlayer/templates/play/upload.html
<!DOCTYPE html>
<html>

	<head>
		<title>Station de partage vidéo</title>
		<meta charset="utf-8" />
		<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
		<link rel="stylesheet" type="text/css" href="/static/css/upload.css">
	</head>

	<body>
		<div class="contact">
			<div id="loading" style="width:100%;height:100%;text-align: center;display:none;">
				<b style="margin-top: 30px">Mise en ligne de la vidéo, veuillez ne pas fermer la page ...</b>
				<img src="/static/img/loading.gif" draggable="false" style="width:100%;height:100%;" />
			</div>
			<form style="" name="form" method="post" action="{{ url_for('play.doupload') }}" enctype="multipart/form-data">
				<a style="float:right" href="{{ url_for('play.index') }}">revenir</a>
				<ul>
					<li>
						<label>Sharer：</label>
						<input type="text" name="author" placeholder="veuillez entrer le nom d'utilisateur" onblur="checkna()" autocomplete="off" required/><span class="tips" id="divname">1~5 caractères de longueur</span>
					</li>
					<li>
						<label>Titre：</label>
						<input type="text" name="title" placeholder="Veuillez saisir le titre de la vidéo" onblur="checktle()" autocomplete="off" required/><span class="tips" id="divpd1">1~20 caractères de longueur</span>
					</li>
					<!--<li>
                <label>la description：</label>
                <input type="text" name="description" placeholder="Veuillez saisir la description de la vidéo" required/><span
                    class="tips" id="divpd2">1 ~ 20 caractères de longueur</span>
            </li>-->
					<!--<li>
                <label>Dessin joint：</label>
                <input type="file" name="image" accept="image/*" required/>
            </li>-->
					<li>
						<label>vidéo：</label>
						<input type="file" name="video" accept="video/mp4" required/><span>Veuillez utiliser le format mp4</span>
					</li>
				</ul>
				<b class="btn"><input type="submit" value="submit"/>
            <input type="reset" value="Annuler"/></b>
			</form>
		</div>

		<script src="/static/js/jquery-1.12.1.min.js"></script>
		<script src="/static/js/upload.js"></script>
		<script>
			$('form').submit(function() {
				$("form").hide();
				$('#loading').show();
			});
		</script>
	</body>

</html>

VisionPlayer/templates/video.html
<link rel="stylesheet" type="text/css" href="/static/css/detail_p.css">
<link rel="stylesheet" type="text/css" href="http://at.alicdn.com/t/font_u4qz1594lnixusor.css">
<link rel="stylesheet" type="text/css" href="/static/css/barrager.css">
<div class="video_ls">
	<video id="vids">
		Votre navigateur ne prend pas en charge les balises h5, veuillez mettre à jour ou modifier votre navigateur
	</video>

	<div class="title_top">
		Partage de vidéo
	</div>

	<div id="pass">
		<img src="/static/img/zt.png">
	</div>

	<div class="controls">

		<div id="pBar">

			<div class="pBar_bj">

				<div id="buff"></div>

				<div id="pBar_move">

					<div id="pBtn"></div>
				</div>
			</div>
		</div>

		<div class="trol_list">

			<div class="list_1">
				<i class="iconfont icon-kuaitui-copy" onClick="ktui()"></i>
				<i class="iconfont icon-zanting2" id="ztbf"></i>
				<i class="iconfont icon-kuaijin" onClick="kjin()"></i>
			</div>

			<div class="comment">
				<input id="comment" type="text" placeholder="Entrez un commentaire">
			</div>

			<div class="voice">
				<i class="iconfont icon-yinliang" style="float:left;"></i>
				<div class="voicep">
					<div id="vBar">
						<div id="vBar_in"></div>
					</div>
					<div id="vBtn"></div>
				</div>
			</div>

			<div class="vtime">
				<font id="nTime">00:00:00</font>/<em id="aTime">00:00:00</em>
			</div>

			<i id="qp" class="iconfont icon-quanping"></i>
		</div>
	</div>
</div>
<script src="/static/js/jquery.barrager.min.js"></script>
<script type="text/javascript" src="/static/js/socket.io.min.js"></script>
<script>
	var timer;

	function hide_tools() {
		timer = setTimeout(function() {
			$('.controls').fadeOut('slow');
		}, 3000);
	}

	$(".video_ls").mouseleave(function() {
		hide_tools();
	});

	$(".video_ls").mousemove(function() {
		clearTimeout(timer);
		$('.controls').fadeIn();
	});

	/*Obtenir un objet de contrôle*/
	var vids = document.getElementById("vids");
	var sskd = $(".controls").width();

	function ktui() {
		vids.currentTime -= 10;
	}

	function kjin() {
		vids.currentTime += 10;
	}

	/*Lorsque vous cliquez sur l'icône de pause*/
	$("#pass").click(function() {
		$(this).css({
			display: "none"
		});
		$("#ztbf").attr("class", "iconfont icon-zanting");
		vids.play();
	});
	/*Lorsque vous cliquez sur l'icône de pause dans le bouton de contrôle*/
	$("#ztbf").click(function() {
		if(vids.paused) {
			vids.play();
			$("#ztbf").attr("class", "iconfont icon-zanting")
		} else {
			vids.pause();
			$("#ztbf").attr("class", "iconfont icon-zanting2")
		}
	});
	/*Peu importe comment faire une pause ou jouer*/
	vids.onplay = function() {
		$("#pass").css({
			display: "none"
		});
		$("#ztbf").attr("class", "iconfont icon-zanting");
	};
	vids.onpause = function() {
		$("#pass").css({
			display: "block"
		});
		$("#ztbf").attr("class", "iconfont icon-zanting2");
		$("#pBar").on('mouseup', function() {
			$(this).off('mousemove')
		})
	};

	/*Convertisseur de temps*/
	function numFormat(time) {
		time = parseInt(time);
		var h = addZero(Math.floor(time / 3600));
		var m = addZero(Math.floor((time % 3600) / 60));
		var s = addZero(Math.floor(time % 60));
		return h + ":" + m + ":" + s;
	}

	function addZero(num) {
		if(num < 10) {
			return "0" + num;
		} else {
			return '' + num;
		}
	}

	/*Heure actuelle / durée totale (début de la méthode canplay)*/
	vids.oncanplay = function() {
		var aTime = numFormat(vids.duration);
		$("#aTime").html(aTime);
		/*La première étape, la barre de progression se déplace avec le temps (lorsque la souris est cliquée)*/
		vids.ontimeupdate = function() {
			sskd = $(".controls").width();
			var hc = (vids.buffered.end(0) / vids.duration) * sskd;
			$("#buff").css({
				width: hc + 'px'
			});
			var nTime = numFormat(vids.currentTime);
			$("#nTime").html(nTime);
			/*L'heure actuelle est supérieure au temps total multiplié par la longueur totale*/
			var nLengh = (vids.currentTime / vids.duration) * (sskd - 20);
			$("#pBar_move").css({
				width: nLengh + 'px'
			});
		};
		/*La deuxième étape, la barre de progression lorsque vous cliquez dessus*/
		$("#pBar").mousedown(function(e) {
			var cLk = e.clientX;
			/*Distance de clic (cliquez dans la zone de la barre de progression)*/
			var pJl = $("#pBar").offset().left;
			/*Obtenez la distance de la barre de progression à partir de la gauche*/
			var mLengh = cLk - pJl;
			/*Distance déplacée*/
			if(mLengh >= (sskd - 20)) {
				mLengh = (sskd - 20)
			}
			$("#pBar_move").css({
				width: mLengh + 'px'
			});
			/*Changer la distance de la barre de progression*/
			var cTime1 = mLengh / (sskd - 20) * vids.duration;
			vids.currentTime = cTime1;
			var cTime2 = numFormat(cTime1);
			$("#nTime").html(cTime2);
			/*Changer la durée d'affichage du HTML*/
			vids.play();
			var timer;
			/*--------------------------------- Distance de déplacement de la souris ------------ - -------------------------*/
			$(document).on('mousemove', function(e) {
				vids.pause();
				var newLeft = e.clientX - pJl;
				/*Faites glisser la distance*/
				if(newLeft <= 0) {
					newLeft = 0;
				}
				if(newLeft >= (sskd - 20)) {
					newLeft = (sskd - 20)
				}
				var cTime3 = newLeft / (sskd - 20) * vids.duration;
				var cTime4 = numFormat(cTime3);
				$("#pBar_move").css({
					width: newLeft + 'px'
				});
				vids.currentTime = cTime3;
				$("#nTime").html(cTime4);
				timer && clearTimeout(timer);
				timer = setTimeout(function() {
					vids.play();
				}, 1000);
			});
			/*$("#pBar_move").on('mouseup', function () {
			 vids.play();
			 });*/
			/*Faites glisser pour terminer*/
			/*----------------------------------Libération de la souris----------------------------------------*/
			$("body").on('mouseup', function() {
				$(document).off('mousemove');
			})
			/*Relâchez la fin*/
		})
		/*Fin de la méthode mousedown*/
	};
	/*(fin de la méthode canplay)*/

	$(document).keydown(function(event) {
		if(event.keyCode === 37) {
			vids.currentTime -= 10;
		}
		if(event.keyCode === 39) {
			vids.currentTime += 10;
		}
		/*---- Mettre la lecture en pause (en cliquant sur l'espace du clavier) ----*/
		if(event.keyCode === 32) {
			if(vids.paused) {
				vids.play();
				$("#ztbf").attr("class", "iconfont icon-zanting")
			} else {
				vids.pause();
				$("#ztbf").attr("class", "iconfont icon-zanting2")
			}
		}
		/*-----------Quitter le mode plein écran-----------*/
		if(event.keyCode === 27) {
			$(".video_ls").removeClass("on");
			$(".controls").css({
				width: "764px"
			})
		}
	});
	/*Événement de double-clic de souris (double-cliquez sur le joueur puis plein écran)*/
	//      $(".video_ls").dblclick(function () {
	//          if ($(".video_ls").hasClass('on')) {
	//              $(".video_ls").removeClass("on");
	//              $(".controls").css({width: "764px"})
	//          } else {
	//              $(".video_ls").addClass("on");
	//              var oBox = $("body").width() - 66;
	//              $(".controls").css({width: oBox + 'px'})
	//          }
	//      });
	/*Bouton de lecture plein écran*/
	$("#qp").click(function() {
		if($(".video_ls").hasClass("on")) {
			$(".video_ls").removeClass("on");
			$(".controls").css({
				width: "764px"
			})
		} else {
			$(".video_ls").addClass("on");
			var oBox = $("body").width() - 66;
			$(".controls").css({
				width: oBox + 'px'
			})
		}
	});
	/*Addition et soustraction de volume*/
	vBtn.onmousedown = function(ev) {
		var ev = ev || window.event;
		var xs = ev.clientX - this.offsetLeft;
		document.onmousemove = function(ev) {
			var newLefts = ev.clientX - xs;
			if(newLefts <= 0) {
				newLefts = 0;
			} else if(newLefts >= vBar.offsetWidth - vBtn.offsetWidth) {
				newLefts = vBar.offsetWidth - vBtn.offsetWidth;
			}
			vBtn.style.left = newLefts + "px";
			vBar_in.style.width = (newLefts + 8) + "px";
			var prop = newLefts / (vBar.offsetWidth - vBtn.offsetWidth);
			vids.volume = prop;
		};
		document.onmouseup = function() {
			document.onmousemove = null;
			document.onmouseup = null;
		}
	}

	$(function() {
		var namespace = '/comment';
		var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace);

		$("#comment").keypress(function(e) {
			if(e.which == 13) {
				socket.emit('imessage', {
					data: encodeURI($('#comment').val())
				});
				$('#comment').val('');
			}
		});

		$('#comment').on('input', function() {
			clearTimeout(timer);
		});

		socket.on('message', function(msg) {
			$('body').barrager({
				'href': '#',
				'info': $('<div/>').text(decodeURI(msg.data)).html()
			});
		});
	});
</script>